from __future__ import annotations

import ast
import os
import re
from pathlib import Path
from typing import Dict


def _autoglm_dir() -> Path:
    return Path(os.environ.get("AUTOGLM_DIR", str(Path.home() / "Open-AutoGLM"))).expanduser()


def apps_file() -> Path:
    return _autoglm_dir() / "phone_agent" / "config" / "apps.py"


def _extract_dict(text: str) -> Dict[str, str]:
    # 尝试解析 APP_PACKAGES = {...}
    m = re.search(r"APP_PACKAGES\\s*=\\s*(\\{.*?\\})", text, re.S)
    if not m:
        return {}
    body = m.group(1)
    try:
        data = ast.literal_eval(body)
        if isinstance(data, dict):
            return {str(k): str(v) for k, v in data.items()}
    except Exception:
        return {}
    return {}


def load_app_packages() -> Dict[str, str]:
    path = apps_file()
    if not path.exists():
        return {}
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return {}
    return _extract_dict(text)


def save_app_packages(apps: Dict[str, str]) -> None:
    path = apps_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    content_lines = [
        "# Auto-generated by autoglm-web",
        "APP_PACKAGES = {",
    ]
    for name, pkg in sorted(apps.items()):
        content_lines.append(f"    {name!r}: {pkg!r},")
    content_lines.append("}")
    path.write_text("\\n".join(content_lines) + "\\n", encoding="utf-8")


def add_entries(entries: Dict[str, str]) -> Dict[str, str]:
    data = load_app_packages()
    data.update(entries)
    save_app_packages(data)
    return data
